server:
  port: 8080
spring:
  # 数据库相关配置
  datasource:
    # 指定数据源类型为: 阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库连接相关配置
    url: jdbc:mysql://127.0.0.1:3306/micro_serve?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    # 数据库: 用户名
    username: root
    # 数据库: 密码
    password: root
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid数据源相关的配置
    druid:
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 10
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 200
      # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置
      max-wait: 60000
      # 关闭空闲连接的检测时间间隔，单位毫秒。Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
      time-between-eviction-runs-millis: 60000
      # 连接的最小生存时间.连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 验证数据库服务可用性的sql，用来检测连接是否有效的sql
      validation-query: select 1
      # 建议配置为true，不影响性能，并且保证安全性。 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis， 执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时直接检测连接是否有效。申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时检测连接是否有效。归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      # 连接出错后再尝试连接三次
      connection-error-retry-attempts: 3
      # 数据库服务宕机自动重连机制
      break-after-acquire-failure: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties:  druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        # 过滤不统计的url
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置监控服务器
      stat-view-servlet:
        # 一定要配置true,不配置则是使用默认值false,空白页面
        enabled: true
        # 访问路径 http://ip:8080/druid
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        deny:
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: nsbd
        # 登录密码
        login-password: zxcvbnm66
  # redis 相关配置
  redis:
    # Redis数据库索引（默认为0
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # 端口
    port: 6379
    # 链接超时时间 单位 ms（毫秒）
    timeout: 3000
    # Redis 线程池设置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

# mybatis相关的配置
mybatis:
  # 实体类
  type-aliases-package: com.hui.springbootapi.model.entity
  # mapper xml文件地址；注意:classpath* 指的是扫描所有模块的资源路径
  mapper-locations: classpath:mapper/*.xml

## 开启Swagger的Basic认证功能,默认是false
swagger:
  basic:
    enable:  true
    username: nsbd
    password: zxcvbnm66